services:
  codebeasts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      # Node environment
      - NODE_ENV=production
    restart: unless-stopped
